FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum* ./
RUN go mod download || true
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/aspm-api ./cmd/aspm-api

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/aspm-api /aspm-api
COPY configs /etc/aspm
EXPOSE 8080
ENTRYPOINT ["/aspm-api"]
