// Package deptrack provides a client for the Dependency-Track REST API v1.
// It implements the "scan-once, monitor-always" workflow described in the PRD:
// SBOMs generated by Syft are uploaded once; Dependency-Track continuously
// monitors them and alerts when new CVEs match any component.
package deptrack

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"time"
)

// Client is a Dependency-Track API v1 client.
type Client struct {
	baseURL    string
	apiKey     string
	httpClient *http.Client
}

// New returns a Client targeting baseURL (e.g. "https://deptrack.example.com").
// apiKey is the Dependency-Track API key with BOM_UPLOAD and PROJECT_READ
// permissions.
func New(baseURL, apiKey string) *Client {
	return &Client{
		baseURL: baseURL,
		apiKey:  apiKey,
		httpClient: &http.Client{
			Timeout: 60 * time.Second,
		},
	}
}

// ProjectInfo is a minimal Dependency-Track project descriptor.
type ProjectInfo struct {
	UUID    string `json:"uuid"`
	Name    string `json:"name"`
	Version string `json:"version"`
}

// Finding mirrors a Dependency-Track /api/v1/finding/project/{uuid} entry.
type Finding struct {
	Component struct {
		Name    string `json:"name"`
		Version string `json:"version"`
		PURL    string `json:"purl"`
	} `json:"component"`
	Vulnerability struct {
		VulnID   string  `json:"vulnId"`
		Severity string  `json:"severity"`
		CVSSv3   float64 `json:"cvssV3BaseScore"`
		Title    string  `json:"title"`
	} `json:"vulnerability"`
}

// EnsureProject looks up a project by name+version, creating it if absent.
// Returns the project UUID.
func (c *Client) EnsureProject(ctx context.Context, name, version string) (string, error) {
	// Attempt lookup first.
	req, err := c.newRequest(ctx, http.MethodGet,
		fmt.Sprintf("/api/v1/project?name=%s&version=%s", name, version), nil)
	if err != nil {
		return "", err
	}
	var projects []ProjectInfo
	if err := c.do(req, &projects); err != nil {
		return "", err
	}
	if len(projects) > 0 {
		return projects[0].UUID, nil
	}

	// Create it.
	body, _ := json.Marshal(map[string]string{"name": name, "version": version})
	req, err = c.newRequest(ctx, http.MethodPut, "/api/v1/project", bytes.NewReader(body))
	if err != nil {
		return "", err
	}
	var created ProjectInfo
	if err := c.do(req, &created); err != nil {
		return "", err
	}
	return created.UUID, nil
}

// UploadBOM sends a CycloneDX BOM (JSON bytes) to Dependency-Track for the
// given project UUID. Dependency-Track processes it asynchronously; callers
// poll GetFindings later to retrieve results.
func (c *Client) UploadBOM(ctx context.Context, projectUUID string, cycloneDXJSON []byte) error {
	payload := map[string]string{
		"project": projectUUID,
		"bom":     base64.StdEncoding.EncodeToString(cycloneDXJSON),
	}
	body, _ := json.Marshal(payload)
	req, err := c.newRequest(ctx, http.MethodPut, "/api/v1/bom", bytes.NewReader(body))
	if err != nil {
		return err
	}
	return c.do(req, nil)
}

// GetFindings returns all current vulnerability findings for the project.
// This is the poll endpoint for "scan-once, monitor-always" logic: callers
// can invoke it on a schedule without uploading a new BOM every time.
func (c *Client) GetFindings(ctx context.Context, projectUUID string) ([]Finding, error) {
	req, err := c.newRequest(ctx, http.MethodGet,
		fmt.Sprintf("/api/v1/finding/project/%s", projectUUID), nil)
	if err != nil {
		return nil, err
	}
	var findings []Finding
	if err := c.do(req, &findings); err != nil {
		return nil, err
	}
	return findings, nil
}

func (c *Client) newRequest(ctx context.Context, method, path string, body *bytes.Reader) (*http.Request, error) {
	var req *http.Request
	var err error
	if body != nil {
		req, err = http.NewRequestWithContext(ctx, method, c.baseURL+path, body)
	} else {
		req, err = http.NewRequestWithContext(ctx, method, c.baseURL+path, nil)
	}
	if err != nil {
		return nil, err
	}
	req.Header.Set("X-Api-Key", c.apiKey)
	req.Header.Set("Content-Type", "application/json")
	return req, nil
}

func (c *Client) do(req *http.Request, out any) error {
	resp, err := c.httpClient.Do(req)
	if err != nil {
		return err
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode >= 300 {
		return fmt.Errorf("dependency-track: status %d for %s %s", resp.StatusCode, req.Method, req.URL.Path)
	}
	if out != nil {
		return json.NewDecoder(resp.Body).Decode(out)
	}
	return nil
}
