name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '1.22' }
      - run: go vet ./...
      - run: go test ./... -count=1

  self-scan:
    runs-on: ubuntu-latest
    needs: go
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '1.22' }
      - name: Install scanners
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh  | sh -s -- -b /usr/local/bin
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
          pipx install semgrep
      - name: Build supplychain-kit
        run: go build -o bin/supplychain-kit ./cmd/supplychain-kit
      - name: Self-scan + Quality Gate
        run: |
          ./bin/supplychain-kit scan --repo . --out findings.json
          ./bin/supplychain-kit gate --findings findings.json --policy configs/policy-moderate.yaml
